language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install coverage
  - pip install prettytable

script: python setup.py test

after_success:
  - coverage run setup.py test
  - coverage html
  - coveralls
