language: python
python:
  - "2.7"

install:
  - pip install coverage
  - pip install prettytable
  - pip install PySerial

script: python setup.py test

after_success:
  - coverage run setup.py test
  - coverage html
