version: 2.1
commands:
    run_tests:
        description: "Run tests for << parameters.working_directory >>"
        parameters:
            working_directory:
                type: string
        steps:
            - run:
                name: "Install test requirements for \"<< parameters.working_directory >>\""
                working_directory: << parameters.working_directory >>
                command: pip install --user -r test_requirements.txt
            - run:
                name: "Run tests for \"<< parameters.working_directory >>\""
                working_directory: << parameters.working_directory >>
                command: python -m coverage run setup.py test
    install_mbed_os_tools:
        description: "Install mbed-os-tools for legacy package testing"
        steps:
            - run:
                name: "Install mbed-os-tools for legacy package testing"
                command: pip install --user .
    setup_and_run_tests:
        steps:
            - checkout
            - run_tests:
                working_directory: .
            - install_mbed_os_tools
            - run_tests:
                working_directory: legacy/mbed-greentea
            - run_tests:
                working_directory: legacy/mbed-ls
    enforce_style:
        steps:
            - checkout
            - run:
                name: Install flake 8
                command: pip install --user flake8
            - run:
                name: Enforce styling
                command: python -m flake8
    combine_and_send_coverage:
        steps:
            - run:
                name: Combine all coverage results
                command: python -m coverage combine .coverage legacy/*/.coverage
            - run:
                name: Send coverage results to coveralls
                command: python -m coveralls
jobs:
    test_python27:
        docker:
            - image: python:2.7-stretch
        steps:
            - setup_and_run_tests
    test_python35:
        docker:
            - image: python:3.5-stretch
        steps:
            - setup_and_run_tests
    test_python36:
        docker:
            - image: python:3.6-stretch
        steps:
            - setup_and_run_tests
    test_python37:
        docker:
            - image: python:3.7-stretch
        steps:
            - setup_and_run_tests
            - combine_and_send_coverage

    style_enforcement:
        docker:
            - image: python:3.7-stretch
        steps:
            - enforce_style
workflows:
    version: 2
    test:
        jobs:
          - test_python27
          - test_python35
          - test_python36
          - test_python37
          - style_enforcement
